// Generated by https://quicktype.io

export interface UniqueProduct {
    data: UniqueProductData;
    meta: Meta;
}

export interface UniqueProductData {
    id:         number;
    attributes: PurpleAttributes;
}

interface PurpleAttributes {
    nombre:      string;
    descripcion: string;
    disponible:  boolean;
    existencias: number;
    precio:      number;
    createdAt:   string;
    updatedAt:   string;
    publishedAt: string;
    categoria:   Categoria;
    imagenes:    Imagenes;
}

interface Categoria {
    data: CategoriaData;
}

interface CategoriaData {
    id:         number;
    attributes: FluffyAttributes;
}

interface FluffyAttributes {
    nombre:      string;
    createdAt:   string;
    updatedAt:   string;
    publishedAt: string;
}

interface Imagenes {
    data: Datum[];
}

interface Datum {
    id:         number;
    attributes: DatumAttributes;
}

interface DatumAttributes {
    name:              string;
    alternativeText:   null;
    caption:           null;
    width:             number;
    height:            number;
    formats:           Formats;
    hash:              string;
    ext:               string;
    mime:              string;
    size:              number;
    url:               string;
    previewUrl:        null;
    provider:          string;
    provider_metadata: ProviderMetadata;
    createdAt:         string;
    updatedAt:         string;
}

interface Formats {
    thumbnail: Large;
    medium:    Large;
    small:     Large;
    large:     Large;
}

interface Large {
    name:              string;
    hash:              string;
    ext:               string;
    mime:              string;
    path:              null;
    width:             number;
    height:            number;
    size:              number;
    url:               string;
    provider_metadata: ProviderMetadata;
}

interface ProviderMetadata {
    public_id:     string;
    resource_type: string;
}

interface Meta {
}
